name: Validate-YAML-Open-Concept-List

on:
  push:
    branches: [ main ]
    paths: ['_data/open.yml']
  pull_request:
    branches: [ main ]
    paths: ['_data/open.yml']

jobs:
  validate-yaml-open-concept-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML intent lists
        run: yamllint -c _data/_config_yamllint.yml _data/open.yml
