name: Validate-YAML-lists

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml-core-concept-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML intent lists
        run: yamllint -c _data/_config_yamllint.yml _data/core.yml
  validate-yaml-open-concept-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML intent lists
        run: yamllint -c _data/_config_yamllint.yml _data/open.yml
  validate-yaml-properties-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML intent lists
        run: yamllint -c _data/_config_yamllint.yml _data/core-properties.yml